Repository gerrymanoim/exchange_calendars, pull requests merged in 2021-07, with the labels that each got.

#41 BUG: Fix errors / warnings related to pandas 1.3.0
  exchange_calendars/calendar_helpers.py
  exchange_calendars/exchange_calendar.py
Labels: bug

#44 BLD: Bump requirements_locked.txt
  etc/requirements_locked.txt
Labels: build

#47 BLD: See if dependabot can manage requirement bumps
  .github/dependabot.yml
Labels: build

#54 ENH: Expose calendar kwargs and handle out-of-bounds
  exchange_calendars/calendar_utils.py
  exchange_calendars/exchange_calendar.py
  exchange_calendars/exchange_calendar_aixk.py
  exchange_calendars/exchange_calendar_xhkg.py
  exchange_calendars/exchange_calendar_xkrx.py
  exchange_calendars/exchange_calendar_xtks.py
  exchange_calendars/precomputed_exchange_calendar.py
  exchange_calendars/us_futures_calendar.py
  tests/test_aixk_calendar.py
  tests/test_always_open.py
  tests/test_calendar_dispatcher.py
  tests/test_exchange_calendar.py
  tests/test_weekday_calendar.py
  tests/test_xbom_calendar.py
  tests/test_xhkg_calendar.py
  tests/test_xkrx_calendar.py
  tests/test_xnys_calendar.py
  tests/test_xses_calendar.py
  tests/test_xshg_calendar.py
  tests/test_xtae_calendar.py
  tests/test_xtks_calendar.py
Labels: enhancement

#65 Improve parsing
  exchange_calendars/calendar_helpers.py
  exchange_calendars/calendar_utils.py
  exchange_calendars/errors.py
  exchange_calendars/exchange_calendar.py
  tests/test_calendar_helpers.py
Labels: enhancement

#62 MAINT: Specify python requires in setup.py
  README.md
  setup.py
Labels: maintenance
