Repository gerrymanoim/exchange_calendars, pull requests merged in 2023-09, with the labels that each got.

#330 XSHG: Add 2023-10-06 as a holiday
  exchange_calendars/exchange_calendar_xshg.py
  tests/resources/xshg.csv
Labels: calendar update

#332 Fix typo in gh release workflow
  .github/workflows/release.yml
Labels: CI

#334 Update tutorials
  docs/tutorials/minutes.ipynb
  docs/tutorials/trading_index.ipynb
Labels: documentation
