Repository gerrymanoim/exchange_calendars, pull requests merged in 2025-01, with the labels that each got.

#442 Update dependencies / update test dates
  etc/requirements.txt
  etc/requirements_dev.txt
  etc/requirements_minpandas.txt
  tests/test_calendar_helpers.py
  tests/test_xbom_calendar.py
  tests/test_xkrx_calendar.py
  tests/test_xses_calendar.py
Labels: dependencies, tests

#445 Fix XSAU `bound_max` error msg.
  exchange_calendars/exchange_calendar_xsau.py
Labels: fix

#446 Add Luxembourg stock exchange
  README.md
  exchange_calendars/calendar_utils.py
  exchange_calendars/exchange_calendar_xlux.py
  tests/resources/xlux.csv
  tests/test_xlux_calendar.py
Labels: enhancement

#443 Bump max Python version to 3.13
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies, maintenance
